[services]
gog = False
egs = True
ea_app = False
ubisoft = False
steam = False
itchio = True

[lutris]
library_ignores = 
migration_version = 17
hide_client_on_game_start = True
discord_rpc = True
show_advanced_options = True
width = 899
height = 600
window_x = 45
window_y = 45
maximized = False
selected_category = service:itchio
installer_create_menu_shortcut = True
sidebar_collapsed_sections = 
icon_type_gridview_itchio = banner_med
hide_text_under_icons = True
view_type = grid
icon_type_listview_itchio = banner

[list view]
name_column_width = 200
year_column_width = 60
runner_column_width = 120
platform_column_width = 120
lastplayed_column_width = 120
playtime_column_width = 100
installedat_column_width = 120

