IgnorePath '**/lost+found'				# Folders used by ext4 during fsck

IgnorePath '/boot/EFI/*'				# Unified Kernel Images for systemd-boot -- we are not using them
IgnorePath '/boot/vmlinuz-*'			# Kernels
IgnorePath '/boot/initramfs-*'			# initramfs
IgnorePath '/boot/loader/entries.srel'	# systemd-boot file indicating a UAPI standards-compliant boot loader implementation

IgnorePath '/efi/EFI/*'					# systemd-boot installation
IgnorePath '/efi/loader/keys'			# systemd-boot Secure Boot variables -- unused
IgnorePath '/efi/loader/random-seed'	# systemd-boot seed for early boot entropy pool provisioning

IgnorePath '/etc/.pwd.lock'				# Lockfile
IgnorePath '/etc/.updated'				# Autogenerated by systemd
IgnorePath '/etc/NetworkManager/system-connections/*' 	# Network connections, might unignore later when passwords are not in plain text
IgnorePath '/etc/adjtime' 				# System clock adjustment
IgnorePath '/etc/audisp' 				# Audit dispatcher
IgnorePath '/etc/audit/*' 				# Audit system
IgnorePath '/etc/ca-certificates/*' 	# Certificate Authority certificates
IgnorePath '/etc/group' 				# Groups info
IgnorePath '/etc/group-' 				# /etc/group backup
IgnorePath '/etc/gshadow' 				# Groups password info
IgnorePath '/etc/gshadow-' 				# /etc/gshadow backup
IgnorePath '/etc/ld.so.cache' 			# Cached list of candidate shared objects (dynamic libraries used by the dynamic linker)
IgnorePath '/etc/machine-id'			# Autogenerated
IgnorePath '/etc/os-release' 			# Autogenerated
IgnorePath '/etc/pacman.d/gnupg/*' 		# Pacman keys
IgnorePath '/etc/pacman.d/mirrorlist' 	# List of pacman mirrors -- automatically generated
IgnorePath '/etc/passwd' 				# Users info
IgnorePath '/etc/passwd-' 				# /etc/passwd backup
IgnorePath '/etc/shadow' 				# Users passwd info
IgnorePath '/etc/shadow-' 				# /etc/shadow backup
IgnorePath '/etc/shells' 				# Valid login shells
IgnorePath '/etc/ssl/certs/*' 			# SSL certificates, links to /etc/ca-certificates/extracted
IgnorePath '/etc/ssl/private'			# Private SSL keys
IgnorePath '/etc/subgid' 				# Subordinate groups
IgnorePath '/etc/subgid-' 				# /etc/subgid backup
IgnorePath '/etc/subuid' 				# Subordinate users
IgnorePath '/etc/subuid-' 				# /etc/subuid backup

IgnorePath '/usr/*'					    # System-wide, readonly files, managed by pacman

IgnorePath '/var/*' 					# Variable data
